models.py
from flask_sqlalchemy import SQLAlchemy

import datetime

db = SQLAlchemy()
class Alumno(db.Model):
    __tablename__ = 'alumnos'
    id = db.Column(db.Integer,primary_key = True)
    nombre = db.Column(db.String(50))
    apellidos = db.Column(db.String(200))
    email = db.Column(db.String(120))
    telefono = db.Column(db.String(20))
    crcreated_date = db.Column(db.DateTime, default = datetime.datetime.now)
    
class Maestros(db.Model):
    __tablename__ = 'maestros'
    matricula = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(50))
    apellidos = db.Column(db.String(50))
    especialidad = db.Column(db.String(50))
    email = db.Column(db.String(50))

forms.py
from wtforms import Form 
from wtforms import StringField, IntegerField, DateField, EmailField

from wtforms import validators 

class UserForm(Form):
    # lo que aparece en el html 
    id = IntegerField("Matricula", [
        validators.DataRequired(message="El campo es requerido"),
        validators.NumberRange(min=100, max=1000, message="ingrese un valor valido")
    ])

    nombre = StringField("Nombre", [
        validators.DataRequired(message="El campo es requerido"), 
    ])
    
    apellidos = StringField("Apellidos",[
        validators.DataRequired(message="El campo es requerido")
    ])
    especialidad = StringField("Apellidos",[
        validators.DataRequired(message="El campo es requerido")
    ])
    email = EmailField("Email", [
        validators.DataRequired(message="El campo es requerido")
    ])
    telefono = StringField("Telefono",[
        validators.DataRequired(message="El campo es requerido")
    ])
    created_date = DateField("created_date", [
        validators.DataRequired(message="Ingrese un correo valido")
    ])

app.py
from wtforms.validators import email
from flask import Flask, render_template, request, redirect, url_for, flash, g
from flask_wtf.csrf import CSRFProtect
from flask_migrate import Migrate, migrate
from config import DevelopmentConfig
import forms
from models import db, Alumno
from maestros.routes import maestros

app = Flask(__name__)
app.config.from_object(DevelopmentConfig)
app.register_blueprint(maestros)
db.init_app(app)
csrf = CSRFProtect()
migrate = Migrate(app,db)

@app.route("/", methods = ['GET', 'POST'])
@app.route("/index")
def index():
    create_form = forms.UserForm(request.form)
    alumno = Alumno.query.all()
    
    return render_template("index.html", form = create_form, alumno = alumno)

@app.errorhandler(404)
def page_not_found(e):
	return render_template("404.html"),404

@app.route("/alumnos", methods = ['GET', 'POST'])
def alumnos():
    create_form = forms.UserForm(request.form)
    
    if request.method == 'POST':
        alumn = Alumno(nombre = create_form.nombre.data,
                       apellidos = create_form.apellidos.data,
                       email = create_form.email.data,
                       telefono = create_form.telefono.data,)
        db.session.add(alumn)
        db.session.commit()
        return redirect(url_for('index'))
    
    return render_template("alumnos.html", form=create_form)

@app.route("/detalles", methods = ['GET', 'POST'])
def detalles():
    create_form = forms.UserForm(request.form)
    
    if request.method == 'GET':
        id = request.args.get('id')
        alumn1 = db.session.query(Alumno).filter(Alumno.id == id).first()
        nombre = alumn1.nombre
        apellidos = alumn1.apellidos
        email = alumn1.email
        telefono = alumn1.telefono

    return render_template("detalles.html", nombre = nombre, apellidos = apellidos, email = email, telefono = telefono )

@app.route("/modificar", methods = ['GET', 'POST'])
def modificar():
    create_form = forms.UserForm(request.form)
    
    if request.method == 'GET':
        id = request.args.get('id')
        alumn1 = db.session.query(Alumno).filter(Alumno.id == id).first()
        create_form.id.data = request.args.get('id')
        create_form.nombre.data = alumn1.nombre
        create_form.apellidos.data = alumn1.apellidos
        create_form.email.data = alumn1.email
        create_form.telefono.data = alumn1.telefono
    if request.method == 'POST':
        id = create_form.id.data
        alumn1 = db.session.query(Alumno).filter(Alumno.id == id).first()
        alumn1.nombre = str.rstrip(create_form.nombre.data)
        alumn1.apellidos = create_form.apellidos.data
        alumn1.email = create_form.email.data
        alumn1.telefono = create_form.telefono.data
        db.session.add(alumn1)
        db.session.commit()
        return redirect(url_for('index'))
    
    return render_template("modificar.html", form=create_form)

@app.route("/eliminar", methods = ['GET', 'POST'])
def eliminar():
    create_form = forms.UserForm(request.form)
    
    if request.method == 'GET':
        id = request.args.get('id')
        alumn1 = db.session.query(Alumno).filter(Alumno.id == id).first()
        create_form.id.data = request.args.get('id')
        create_form.nombre.data = alumn1.nombre
        create_form.apellidos.data = alumn1.apellidos
        create_form.email.data = alumn1.email
        create_form.telefono.data = alumn1.telefono
    if request.method == 'POST':
        id = create_form.id.data
        alumn1 = db.session.query(Alumno).filter(Alumno.id == id).first()
        db.session.delete(alumn1)
        db.session.commit()
        return redirect(url_for('index'))
    
    return render_template("eliminar.html", form=create_form)


if __name__ == '__main__':
    csrf.init_app(app)
    with app.app_context():
        db.create_all()
    app.run(debug=True)

maestros/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from models import Maestros, db

maestros = Blueprint("maestros", __name__)


@maestros.route("/maestros", methods=["GET"])
def maestros_index():
    lista_maestros = Maestros.query.all()
    return render_template("indexMaestros.html", maestros=lista_maestros)


@maestros.route("/maestros/nuevo", methods=["GET", "POST"])
def agregar_maestro():
    if request.method == "POST":
        nuevo_maestro = Maestros(
            nombre=request.form.get("nombre"),
            apellidos=request.form.get("apellidos"),
            especialidad=request.form.get("especialidad"),
            email=request.form.get("email"),
        )
        db.session.add(nuevo_maestro)
        db.session.commit()
        return redirect(url_for("maestros.maestros_index"))

    return render_template("nuevoMaestro.html")

@maestros.route("/maestros/detalles", methods=["GET"])
def detalles_maestro():
    matricula = request.args.get("matricula", type=int)
    maestro = Maestros.query.filter_by(matricula=matricula).first_or_404()
    return render_template("detallesMaestro.html", maestro=maestro)


@maestros.route("/maestros/modificar", methods=["GET", "POST"])
def modificar_maestro():
    if request.method == "POST":
        matricula = request.form.get("matricula", type=int)
        maestro = Maestros.query.filter_by(matricula=matricula).first_or_404()
        maestro.nombre = request.form.get("nombre")
        maestro.apellidos = request.form.get("apellidos")
        maestro.especialidad = request.form.get("especialidad")
        maestro.email = request.form.get("email")
        db.session.commit()
        return redirect(url_for("maestros.maestros_index"))

    matricula = request.args.get("matricula", type=int)
    maestro = Maestros.query.filter_by(matricula=matricula).first_or_404()
    return render_template("modificarMaestro.html", maestro=maestro)


@maestros.route("/maestros/eliminar", methods=["GET", "POST"])
def eliminar_maestro():
    if request.method == "POST":
        matricula = request.form.get("matricula", type=int)
        maestro = Maestros.query.filter_by(matricula=matricula).first_or_404()
        db.session.delete(maestro)
        db.session.commit()
        return redirect(url_for("maestros.maestros_index"))

    matricula = request.args.get("matricula", type=int)
    maestro = Maestros.query.filter_by(matricula=matricula).first_or_404()
    return render_template("eliminarMaestro.html", maestro=maestro)

templates/_macros.html
{% macro campoNuevo(field, clase="form-control") %}

<td>{{field.label}}</td>
<dd>{{field(class_=clase) | safe}}</dd>
{%if field.errors%}
    {%for error in field.errors%}
        <li style="color: red;">{{error}}</li>
    {%endfor%}
    
{%endif%}

{% endmacro %}

templates/alumnos.html
{% extends "layout.html" %}
{%import "_macros.html" as macros%}
{% block container %}


<form class="max-w-sm mx-auto space-y-4">
    <div>
        <label for="visitors" class="block mb-2.5 text-sm font-medium text-heading">ID</label>
        <input type="text" id="visitors" class="bg-neutral-secondary-medium border border-default-medium text-heading text-sm rounded-base focus:ring-brand focus:border-brand block w-full px-2.5 py-2 shadow-xs placeholder:text-body" placeholder="" required />
    </div>
    <div>
        <label for="visitors" class="block mb-2.5 text-sm font-medium text-heading">Nombre</label>
        <input type="text" id="visitors" class="bg-neutral-secondary-medium border border-default-medium text-heading text-sm rounded-base focus:ring-brand focus:border-brand block w-full px-3 py-2.5 shadow-xs placeholder:text-body" placeholder="" required />
    </div>
    <div>
        <label for="visitors" class="block mb-2.5 text-sm font-medium text-heading">Apellido paterno</label>
        <input type="text" id="visitors" class="bg-neutral-secondary-medium border border-default-medium text-heading text-base rounded-base focus:ring-brand focus:border-brand block w-full px-3.5 py-3 shadow-xs placeholder:text-body" placeholder="" required />
    </div>
    <div>
        <label for="visitors" class="block mb-2.5 text-sm font-medium text-heading">Correo</label>
        <input type="email" id="visitors" class="bg-neutral-secondary-medium border border-default-medium text-heading text-base rounded-base focus:ring-brand focus:border-brand block w-full px-4 py-3.5 shadow-xs placeholder:text-body" placeholder="" required />
    </div>
</form>


{%endblock%}

templates/detalles.html
{% extends "layout.html" %}
{%import "_macros.html" as macros%}
{% block container %}



<div class="relative bg-neutral-primary-soft max-w-xs w-full p-6 border border-default rounded-base shadow-xs">
        <button id="dropdownButton" data-dropdown-toggle="dropdown" class="absolute top-2 end-2 text-body hover:text-heading bg-neutral-primary-soft box-border border border-transparent hover:bg-neutral-tertiary focus:ring-4 focus:ring-neutral-tertiary rounded-base p-1.5 focus:outline-none" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-width="3" d="M6 12h.01m6 0h.01m5.99 0h.01"/></svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 bg-neutral-primary-medium border border-default-medium rounded-base shadow-lg w-36 block hidden">
            <ul class="p-2 text-sm text-body font-medium" aria-labelledby="dropdownButton">
                <li>
                    <a href="#" class="inline-flex items-center w-full p-2 hover:bg-neutral-tertiary-medium hover:text-heading rounded-md">Edit</a>
                </li>
                <li>
                    <a href="#" class="inline-flex items-center w-full p-2 hover:bg-neutral-tertiary-medium hover:text-heading rounded-md">Export Data</a>
                </li>
                <li>
                    <a href="#" class="inline-flex items-center w-full p-2 text-fg-danger hover:bg-neutral-tertiary-medium rounded-md">Delete</a>
                </li>
            </ul>
        </div>
    <div class="flex flex-col items-center">
        <img class="w-24 h-24 mb-6 rounded-full" src="/static/img/cuenta.png" alt="Bonnie image"/>
        <h5 class="mb-0.5 text-xl font-semibold tracking-tight text-heading">{{ nombre }} {{ apellidos }}</h5>
        <span class="text-sm text-body">{{ email }}</span>
        <div class="flex mt-4 md:mt-6 gap-4">
            <a href="{{ url_for('index') }}" class="inline-flex self-start w-auto text-body bg-neutral-secondary-medium box-border border border-default-medium hover:bg-neutral-tertiary-medium hover:text-heading focus:ring-4 focus:ring-neutral-tertiary shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none">
                Volver
            </a>
        </div>
    </div>
</div>


{%endblock%}

templates/detallesMaestro.html
{% extends "layout.html" %}
{%import "_macros.html" as macros%}
{% block container %}



<div class="relative bg-neutral-primary-soft max-w-xs w-full p-6 border border-default rounded-base shadow-xs">
        <button id="dropdownButton" data-dropdown-toggle="dropdown" class="absolute top-2 end-2 text-body hover:text-heading bg-neutral-primary-soft box-border border border-transparent hover:bg-neutral-tertiary focus:ring-4 focus:ring-neutral-tertiary rounded-base p-1.5 focus:outline-none" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-width="3" d="M6 12h.01m6 0h.01m5.99 0h.01"/></svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 bg-neutral-primary-medium border border-default-medium rounded-base shadow-lg w-36 block hidden">
            <ul class="p-2 text-sm text-body font-medium" aria-labelledby="dropdownButton">
                <li>
                    <a href="#" class="inline-flex items-center w-full p-2 hover:bg-neutral-tertiary-medium hover:text-heading rounded-md">Edit</a>
                </li>
                <li>
                    <a href="#" class="inline-flex items-center w-full p-2 hover:bg-neutral-tertiary-medium hover:text-heading rounded-md">Export Data</a>
                </li>
                <li>
                    <a href="#" class="inline-flex items-center w-full p-2 text-fg-danger hover:bg-neutral-tertiary-medium rounded-md">Delete</a>
                </li>
            </ul>
        </div>
    <div class="flex flex-col items-center">
        <img class="w-24 h-24 mb-6 rounded-full" src="/static/img/cuenta.png" alt="Bonnie image"/>
        <h5 class="mb-0.5 text-xl font-semibold tracking-tight text-heading">{{ maestro.nombre }} {{ maestro.apellidos }}</h5>
        <span class="text-sm text-body">{{ maestro.email }}</span>
        <span class="text-sm text-body">Especialidad: {{ maestro.especialidad }}</span>
        <span class="text-sm text-body">Matricula: {{ maestro.matricula }}</span>
        <div class="flex mt-4 md:mt-6 gap-4">
            <a href="{{ url_for('maestros.maestros_index') }}" class="inline-flex self-start w-auto text-body bg-neutral-secondary-medium box-border border border-default-medium hover:bg-neutral-tertiary-medium hover:text-heading focus:ring-4 focus:ring-neutral-tertiary shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none">
                Volver
            </a>
        </div>
    </div>
</div>


{%endblock%}

templates/eliminar.html
{% extends "layout.html" %}
{%import "_macros.html" as macros%}
{% block container %}


<form class="max-w-sm mx-auto space-y-4" method="post" action="{{ url_for('eliminar') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <input type="hidden" name="id" value="{{ form.id.data or '' }}">
    {{ macros.campoNuevo(form.nombre, "block py-2.5 px-0 w-full text-sm text-heading bg-transparent border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0 focus:border-brand peer") }}
    {{ macros.campoNuevo(form.apellidos, "block py-2.5 px-0 w-full text-sm text-heading bg-transparent border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0 focus:border-brand peer") }}
    {{ macros.campoNuevo(form.telefono, "block py-2.5 px-0 w-full text-sm text-heading bg-transparent border-0 border-b-2 border-default-medium appearance-none focus:outline-none focus:ring-0 focus:border-brand peer") }}
    {{ macros.campoNuevo(form.email, "bg-neutral-secondary-medium border border-default-medium text-heading text-sm rounded-base focus:ring-brand focus:border-brand block w-full px-3 py-2.5 shadow-xs placeholder:text-body") }}
    <button type="submit" class="w-full rounded-base bg-fg-brand px-4 py-2 text-sm font-medium text-white hover:opacity-90">
        Eliminar 
    </button>
</form>


{%endblock%}

templates/eliminarMaestro.html
{% extends "layout.html" %}
{%import "_macros.html" as macros%}
{% block container %}


<form class="max-w-sm mx-auto space-y-4" method="post" action="{{ url_for('maestros.eliminar_maestro') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <input type="hidden" name="matricula" value="{{ maestro.matricula }}">

    <input
      name="nombre"
      type="text"
      value="{{ maestro.nombre }}"
      readonly
      class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base"
    >
    <input
      name="apellidos"
      type="text"
      value="{{ maestro.apellidos }}"
      readonly
      class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base"
    >
    <input
      name="especialidad"
      type="text"
      value="{{ maestro.especialidad }}"
      readonly
      class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base"
    >
    <input
      name="email"
      type="email"
      value="{{ maestro.email }}"
      readonly
      class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base"
    >
    <button type="submit" class="w-full rounded-base bg-fg-brand px-4 py-2 text-sm font-medium text-white hover:opacity-90">
        Eliminar 
    </button>
</form>


{%endblock%}

templates/index.html
{% extends "layout.html" %}
{%import "_macros.html" as macros%}
{% block container %}



<div class="relative overflow-x-auto bg-neutral-primary-soft shadow-xs rounded-base border border-default">
    <div class="p-4">
        <label for="input-group-1" class="sr-only">Search</label>
        <div class="relative">
            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                <svg class="w-4 h-4 text-body" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="m21 21-3.5-3.5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z"/></svg>
            </div>
            <input type="text" id="input-group-1" class="block w-full max-w-96 ps-9 pe-3 py-2 bg-neutral-secondary-medium border border-default-medium text-heading text-sm rounded-base focus:ring-brand focus:border-brand px-3 py-2.5 shadow-xs placeholder:text-body" placeholder="Search">
        </div>
    </div>
    <div class="p-4">
        
        <div class="relative">
           <a href="alumnos" class="font-medium text-green-500 hover:underline">Agregar</a> 
        </div>
    </div>
    
    <table class="w-full text-sm text-left rtl:text-right text-body">
        <thead class="text-sm text-body bg-neutral-secondary-medium border-b border-t border-default-medium">
            <tr>
                <th scope="col" class="px-6 py-3 font-medium">
                    Nombre
                </th>
                <th scope="col" class="px-6 py-3 font-medium">
                    Apellidos
                </th>
                <th scope="col" class="px-6 py-3 font-medium">
                    Email
                </th>
                <th scope="col" class="px-6 py-3 font-medium">
                    Telefono
                </th>
                <th scope="col" class="px-6 py-3 font-medium">
                    
                </th>
                <th scope="col" class="px-6 py-3 font-medium">
                    
                </th>
                <th scope="col" class="px-6 py-3 font-medium">
                    
                </th>
            </tr>
        </thead>
        <tbody>
            {%for alumn in alumno%}

            <tr class="bg-neutral-primary-soft border-b border-default hover:bg-neutral-secondary-medium">
                <th scope="row" class="px-6 py-4 font-medium text-heading whitespace-nowrap">
                    {{alumn.nombre}}
                </th>
                <td class="px-6 py-4">
                    {{alumn.apellidos}}
                </td>
                <td class="px-6 py-4">
                    {{alumn.email}}
                </td>
                <td class="px-6 py-4">
                    {{alumn.telefono}}
                </td>
                <td class="px-6 py-4">
                    <a href="{{ url_for('detalles', id=alumn.id) }}" class="font-medium text-yellow-500 hover:underline">Detalles</a>
                </td>
                <td class="px-6 py-4">
                    <a href="{{ url_for('modificar', id=alumn.id) }}" class="font-medium text-fg-brand hover:underline">Editar</a>
                </td>
                <td class="px-6 py-4">
                    <a href="{{ url_for('eliminar', id=alumn.id) }}" class="font-medium text-red-500 hover:underline">Eliminar</a>
                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
</div>


    
{% endblock %}

templates/indexMaestros.html
{% extends "layout.html" %} {% block container %}

<div
  class="relative overflow-x-auto bg-neutral-primary-soft shadow-xs rounded-base border border-default"
>
  <div class="p-4">
    <label for="input-group-1" class="sr-only">Search</label>
    <div class="relative">
      <div
        class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none"
      >
        <svg
          class="w-4 h-4 text-body"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          fill="none"
          viewBox="0 0 24 24"
        >
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-width="2"
            d="m21 21-3.5-3.5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z"
          />
        </svg>
      </div>
      <input
        type="text"
        id="input-group-1"
        class="block w-full max-w-96 ps-9 pe-3 py-2 bg-neutral-secondary-medium border border-default-medium text-heading text-sm rounded-base focus:ring-brand focus:border-brand px-3 py-2.5 shadow-xs placeholder:text-body"
        placeholder="Search"
      />
    </div>
  </div>
  <div class="p-4">
    <div class="relative">
      <a
        href="{{ url_for('maestros.agregar_maestro') }}"
        class="font-medium text-green-500 hover:underline"
        >Agregar</a
      >
    </div>
  </div>
  <table class="w-full text-sm text-left rtl:text-right text-body">
    <thead
      class="text-sm text-body bg-neutral-secondary-medium border-b border-t border-default-medium"
    >
      <tr>
        <th scope="col" class="px-6 py-3 font-medium">Matricula</th>
        <th scope="col" class="px-6 py-3 font-medium">Nombre</th>
        <th scope="col" class="px-6 py-3 font-medium">Apellidos</th>
        <th scope="col" class="px-6 py-3 font-medium">Especialidad</th>
        <th scope="col" class="px-6 py-3 font-medium">Email</th>
        <th scope="col" class="px-6 py-3 font-medium"></th>
        <th scope="col" class="px-6 py-3 font-medium"></th>
        <th scope="col" class="px-6 py-3 font-medium"></th>
      </tr>
    </thead>
    <tbody>
      {% for maestro in maestros %}
      <tr
        class="bg-neutral-primary-soft border-b border-default hover:bg-neutral-secondary-medium"
      >
        <td class="px-6 py-4">{{ maestro.matricula }}</td>
        <td class="px-6 py-4">{{ maestro.nombre }}</td>
        <td class="px-6 py-4">{{ maestro.apellidos }}</td>
        <td class="px-6 py-4">{{ maestro.especialidad }}</td>
        <td class="px-6 py-4">{{ maestro.email }}</td>
        <td class="px-6 py-4">
          <a
            href="{{ url_for('maestros.detalles_maestro', matricula=maestro.matricula) }}"
            class="font-medium text-yellow-500 hover:underline"
            >Detalles</a
          >
        </td>
        <td class="px-6 py-4">
          <a
            href="{{ url_for('maestros.modificar_maestro', matricula=maestro.matricula) }}"
            class="font-medium text-fg-brand hover:underline"
            >Editar</a
          >
        </td>
        <td class="px-6 py-4">
          <a
            href="{{ url_for('maestros.eliminar_maestro', matricula=maestro.matricula) }}"
            class="font-medium text-red-500 hover:underline"
            >Eliminar</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

templates/modificarMaestro.html
{% extends "layout.html" %}
{%import "_macros.html" as macros%}
{% block container %}


<form class="max-w-sm mx-auto space-y-4" method="post" action="{{ url_for('maestros.modificar_maestro') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <input type="hidden" name="matricula" value="{{ maestro.matricula }}">

    <input
      name="nombre"
      type="text"
      required
      value="{{ maestro.nombre }}"
      placeholder="Nombre"
      class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base focus:outline-none focus:ring-0 focus:border-brand"
    >
    <input
      name="apellidos"
      type="text"
      required
      value="{{ maestro.apellidos }}"
      placeholder="Apellidos"
      class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base focus:outline-none focus:ring-0 focus:border-brand"
    >
    <input
      name="especialidad"
      type="text"
      required
      value="{{ maestro.especialidad }}"
      placeholder="Especialidad"
      class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base focus:outline-none focus:ring-0 focus:border-brand"
    >
    <input
      name="email"
      type="email"
      required
      value="{{ maestro.email }}"
      placeholder="Email"
      class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base focus:outline-none focus:ring-0 focus:border-brand"
    >
    <button type="submit" class="w-full rounded-base bg-fg-brand px-4 py-2 text-sm font-medium text-white hover:opacity-90">
        Actualizar
    </button>
</form>


{%endblock%}

templates/nuevoMaestro.html
{% extends "layout.html" %} {% block container %}

<form
  class="max-w-sm mx-auto space-y-4"
  method="post"
  action="{{ url_for('maestros.agregar_maestro') }}"
>
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <input
    name="nombre"
    type="text"
    required
    placeholder="Nombre"
    class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base focus:outline-none focus:ring-0 focus:border-brand"
  />

  <input
    name="apellidos"
    type="text"
    required
    placeholder="Apellidos"
    class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base focus:outline-none focus:ring-0 focus:border-brand"
  />

  <input
    name="especialidad"
    type="text"
    required
    placeholder="Especialidad"
    class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base focus:outline-none focus:ring-0 focus:border-brand"
  />

  <input
    name="email"
    type="email"
    required
    placeholder="Email"
    class="block py-2.5 px-3 w-full text-sm text-heading bg-transparent border border-default-medium rounded-base focus:outline-none focus:ring-0 focus:border-brand"
  />

  <button
    type="submit"
    class="w-full rounded-base bg-fg-brand px-4 py-2 text-sm font-medium text-white hover:opacity-90"
  >
    Guardar maestro
  </button>
</form>

{% endblock %}